name: Checks with bmlab from PyPI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      # Display must be available globally for linux to know where xvfb is
      DISPLAY: :0
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup xvfb (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        # start xvfb in the background
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install codecov coverage flake8
        python -m pip install -r tests/requirements.txt
        # install dependencies
        pip install -e .
        # show installed packages
        pip freeze
    - name: Start application and print version
      run: |
        QT_DEBUG_PLUGINS=1 python -m bmicro --version
#    - name: Test with pytest
#      run: |
#        coverage run --source=bmicro -m pytest tests
#    - name: Lint with flake8
#      run: |
#        flake8 .
#    - name: Submit code coverage
#      run: |
#        coverage report -m
#        codecov
    - name: Create app and check if it runs (macOS)
      # For now, we disable this step for Python 3.9, because there is no
      # scipy wheel matching build-recipes/requirements.txt (this is the
      # easy way out). It is important that this step works with the Python
      # version that is set in deploy_github.yml.
      if: runner.os == 'macOS' && matrix.python-version != '3.9'
      working-directory: ./build-recipes
      run: |
        bash ./macos_build_app.sh BMicro $(python -m bmicro --version)
