name: Deploy to GitHub Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12']
        os: [macos-latest, windows-2022]
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .
    - name: Build app for Mac
      if: runner.os == 'macOS'
      working-directory: ./build-recipes
      run: |
        bash ./macos_build_app.sh BMicro $(python -m bmicro --version)
    - name: Build app for Win
      if: runner.os == 'windows'
      working-directory: ./build-recipes
      run: |
        pip install -r win_build_requirements.txt
        pyinstaller -y --log-level=WARN win_BMicro.spec
        .\dist\BMicro\\BMicro.exe --version
        python win_make_iss.py
        iscc /Q win_bmicro.iss
    - name: Release macOS assets
      if: runner.os == 'macOS'
      uses: softprops/action-gh-release@v2
      with:
        name: BMicro ${{ github.ref_name }}
        draft: true
        prerelease: false
        body: |
            ![](https://img.shields.io/github/downloads/BrillouinMicroscopy/BMicro/${{ github.ref_name }}/total.svg)
        files: |
          ./build-recipes/dist/BMicro_${{ github.ref_name }}_macosx.dmg
          ./build-recipes/dist/BMicro_${{ github.ref_name }}_macosx.pkg
    - name: Release windows assets
      if: runner.os == 'windows'
      uses: softprops/action-gh-release@v2
      with:
        name: BMicro ${{ github.ref_name }}
        draft: true
        prerelease: false
        body: |
            ![](https://img.shields.io/github/downloads/BrillouinMicroscopy/BMicro/${{ github.ref_name }}/total.svg)
        files: |
          ./build-recipes/Output/BMicro_${{ github.ref_name }}_win_64bit_setup.exe
